//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace breadpan
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REVIEW()
        {
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
        }
    
        public string ReviewID { get; set; }
        public string TourID { get; set; }
        public string FullName { get; set; }
        public string RDescription { get; set; }
        public int Ratings { get; set; }
    
        public virtual TOUR TOUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
    }
}
