//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace breadpan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public string TransID { get; set; }
        public string UserID { get; set; }
        public string ReviewID { get; set; }
        public string TourID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string TStatus { get; set; }
    
        public virtual REVIEW REVIEW { get; set; }
        public virtual TOUR TOUR { get; set; }
        public virtual USER USER { get; set; }
    }
}
